# Generated by Django 5.2.1 on 2025-05-20 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
                ('channel', models.CharField(max_length=200)),
                ('user', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('ts', models.CharField(max_length=200)),
                ('edited', models.JSONField(blank=True, null=True)),
                ('is_starred', models.BooleanField(blank=True, null=True)),
                ('pinned_to', models.JSONField(blank=True, null=True)),
                ('reactions', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
