# Generated by Django 5.2 on 2025-05-07 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ccserver", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.RenameModel(old_name="UserTag", new_name="ProfileTag",),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slack_username",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "linkedin_username",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "github_username",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "personal_site",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
                ("state", models.CharField(blank=True, max_length=100, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("photo_url", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "employment_status",
                    models.CharField(
                        choices=[
                            ("Employed", "employed"),
                            ("Searching", "searching"),
                            ("Hiring", "hiring"),
                            ("Student", "student"),
                        ],
                        default="Searching",
                        max_length=20,
                    ),
                ),
                ("job_title", models.CharField(blank=True, max_length=100, null=True)),
                ("company", models.CharField(blank=True, max_length=100, null=True)),
                ("bio", models.TextField(blank=True, max_length=600, null=True)),
                (
                    "tags",
                    models.ManyToManyField(
                        related_name="user_tags",
                        through="ccserver.ProfileTag",
                        to="ccserver.tag",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AlterUniqueTogether(name="profiletag", unique_together=set(),),
        migrations.AddField(
            model_name="profiletag",
            name="profile",
            field=models.ForeignKey(
                default="profile_default",
                on_delete=django.db.models.deletion.CASCADE,
                to="ccserver.profile",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="profiletag", unique_together={("profile", "tag")},
        ),
        migrations.DeleteModel(name="User",),
        migrations.RemoveField(model_name="profiletag", name="user",),
    ]
