# Generated by Django 5.2 on 2025-05-07 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "ccserver",
            "0002_alter_event_user_alter_project_user_alter_post_user_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="profiletag",
            name="profile",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="ccserver.profile",
            ),
        ),
    ]
