# Generated by Django 5.2 on 2025-05-21 02:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ccserver", "0003_load_tag_list"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="github_username",
            new_name="github_url",
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="linkedin_username",
            new_name="linkedin_url",
        ),
        migrations.AddField(
            model_name="profile",
            name="email",
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
